# Docker Compose configuration for Calorie Calculator
# Runs PostgreSQL database, Flask API, and React frontend

services:
  # PostgreSQL database service
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: calorie_tracker      # Database name
      POSTGRES_USER: postgres           # Database user
      POSTGRES_PASSWORD: password       # Database password (change in production)
    ports:
      - "5432:5432"                    # Expose database port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Check if database is ready
      interval: 5s
      timeout: 5s
      retries: 5

  # Flask API backend service
  api:
    build: .                           # Build from local Dockerfile
    ports:
      - "8000:8000"                    # Expose API port
    environment:
      # Database connection string for the API
      DATABASE_URL: postgresql://postgres:password@postgres:5432/calorie_tracker
      FLASK_ENV: production
    depends_on:
      postgres:
        condition: service_healthy     # Wait for database to be ready
    restart: on-failure               # Restart if container fails
    command: gunicorn run:app -c gunicorn.conf.py

  # React frontend service
  frontend:
    build: ./frontend                  # Build from frontend Dockerfile
    ports:
      - "3000:3000"                    # Expose frontend port
    environment:
      REACT_APP_API_URL: http://localhost:8000/api  # API endpoint for frontend
    depends_on:
      - api                           # Wait for API to be ready

# Named volume for database persistence
volumes:
  postgres_data:
